locals {
  # An empty app cluster kubeconfig means the applications run on the cluster the platform itself
  # runs on, which is the single-cluster case.
  app_cluster_kubeconfig = var.app_cluster_kubeconfig != "" ? var.app_cluster_kubeconfig : var.ai_cluster_kubeconfig

  # Every name under `apps_domain` already resolves to the ingress load balancer and is already
  # covered by the wildcard certificate, so publishing the gateway is one Ingress and nothing else.
  litellm_hostname   = "${var.litellm_hostname_label}.${var.apps_domain}"
  litellm_public_url = "https://${local.litellm_hostname}"

  # The gateway's OpenAI-compatible routes live under '/v1'. `ai/model-access` appends the suffix
  # itself, so the platform-level URL stays without it.
  litellm_api_base = local.litellm_public_url
}

# --- Generated secrets --------------------------------------------------------------------------
#
# Neither of these is an input. A credential that only ever moves between two modules of one run has
# no reason to be handed around outside it, and a building block output cannot be sensitive.

resource "random_password" "litellm_master_key" {
  length = 48
  # The master key is sent as a bearer token and ends up in a Kubernetes Secret, an environment
  # variable and a provider configuration. Alphanumeric keeps it safe in all three.
  special = false
}

resource "random_password" "clickhouse_admin" {
  length = 32
  # Each tenant's DDL Job passes this password to `clickhouse-client` on a command line, so a
  # special character would have to survive shell quoting to reach the server.
  special = false
}

locals {
  # LiteLLM rejects a key without the 'sk-' prefix. It is the root credential of the gateway: it
  # authenticates every call to the /key and /team endpoints and works as a virtual key itself.
  #
  # An operator reads it from the Secret in the gateway namespace, named by the
  # `litellm_master_key_secret` output. It is deliberately not an output of this building block,
  # because `version_spec.outputs` has no `sensitive` block and every output is stored and shown in
  # cleartext in meshPanel.
  litellm_master_key = "sk-${random_password.litellm_master_key.result}"
}

# --- The gateway's own database, inside the shared instance -------------------------------------
#
# The gateway keeps virtual keys, teams, budgets and spend records in Postgres, and the Prisma
# migration Job creates the tables inside a database that already exists — never the database
# itself. `existing_instance_id` selects the submodule's database-only mode, so this run creates the
# database and its owner user and touches nothing about the shared instance.
#
# The password is generated by STACKIT and never becomes an input. One consequence is worth knowing:
# the chart substitutes it into the connection URL without percent-encoding, so a password
# containing ':', '@', '/' or '?' breaks the URL. Should STACKIT ever generate such a password, the
# way out is to have STACKIT generate a new one for the user.
module "litellm_database" {
  source = "github.com/meshcloud/meshstack-hub//modules/stackit/postgresflex/buildingblock/database?ref=${var.hub.git_ref}"

  project_id     = var.stackit_project_id
  stackit_region = local.stackit_region

  existing_instance_id = var.stackit_postgres_instance_id

  database_name     = var.litellm_database_name
  database_username = var.litellm_database_name

  # `prisma migrate deploy` creates and alters tables inside a database the user owns and never
  # creates a database, so `createdb` would only let the gateway create databases outside its scope.
  database_user_roles = ["login"]
}

# --- The gateway ---------------------------------------------------------------------------------
#
# One installation for the whole platform. It is the component that manages model access: virtual
# keys, teams, budgets and the model allow-list all live here, and it is what hides the shape of the
# backends from every tenant.
module "litellm" {
  source = "github.com/meshcloud/meshstack-hub//modules/ai/litellm/buildingblock?ref=${var.hub.git_ref}"

  cluster_endpoint       = local.ai_cluster_endpoint
  cluster_ca_certificate = local.ai_cluster_ca_certificate_base64
  token                  = local.ai_cluster_token
  client_certificate     = local.ai_cluster_client_certificate_pem
  client_key             = local.ai_cluster_client_key_pem

  namespace     = var.litellm_namespace
  replica_count = var.litellm_replica_count

  master_key = local.litellm_master_key

  # The Ingress below terminates TLS on this name, and the proxy builds its SSO callback from it.
  public_url = local.litellm_public_url

  model_backends         = var.litellm_model_backends
  model_backend_api_keys = var.litellm_model_backend_api_keys

  postgres_host     = module.litellm_database.host
  postgres_port     = module.litellm_database.port
  postgres_database = module.litellm_database.database_name
  postgres_username = module.litellm_database.username
  postgres_password = module.litellm_database.password

  # Cross-pod rate limits and spend tracking. Off by default, because the gateway takes no database
  # index and would share the keyspace the tracing instances are separated in.
  redis_host     = var.litellm_redis_enabled ? var.valkey_host : null
  redis_port     = var.valkey_port
  redis_password = var.litellm_redis_enabled ? var.valkey_password : null

  # Native SSO, no oauth2-proxy. The console holds at most five users on the free open-source proxy.
  oidc = var.litellm_console_sso_enabled ? {
    issuer_url    = var.oidc.issuer_url
    client_id     = var.oidc.client_id
    client_secret = var.oidc.client_secret
    scopes        = var.oidc.scopes

    authorization_endpoint = var.oidc.authorization_endpoint
    token_endpoint         = var.oidc.token_endpoint
    userinfo_endpoint      = var.oidc.userinfo_endpoint

    allowed_email_domains = var.oidc.allowed_email_domains
    proxy_admin_id        = var.oidc.proxy_admin_id
    logout_url            = var.oidc.logout_url
    auto_redirect_to_sso  = var.oidc.auto_redirect_to_sso
  } : null
}

# The one Ingress this architecture creates. The Kubernetes architecture below it already delivers a
# working HTTPS hostname: `<label>.<apps_domain>` resolves to the ingress load balancer and the
# controller serves the wildcard certificate for it as its default. So there is no `tls` block, no
# cert-manager annotation and no DNS record — adding the Ingress is all it takes to publish a
# service here.
resource "kubernetes_ingress_v1" "litellm" {
  metadata {
    name      = "litellm"
    namespace = module.litellm.namespace

    labels = {
      "app.kubernetes.io/managed-by" = "meshstack"
      "app.kubernetes.io/part-of"    = "ai-platform"
    }
  }

  spec {
    ingress_class_name = var.ingress_class_name

    rule {
      host = local.litellm_hostname

      http {
        path {
          path      = "/"
          path_type = "Prefix"

          backend {
            service {
              name = module.litellm.service_name
              port {
                # The gateway module owns the port and reports it, so this composition repeats no
                # number the chart could change under it.
                number = module.litellm.service_port
              }
            }
          }
        }
      }
    }
  }
}

# --- The shared ClickHouse cluster ---------------------------------------------------------------
#
# One cluster per AI platform cluster, shared by every tenant's tracing instance. Each tenant gets a
# database and a user of its own inside it, created by `ai/model-access` when the tenant is created.
# The administrative password never leaves this cluster: the module holds it in a Secret that each
# tenant's DDL Job mounts, so it is not an input of the tenant-facing definition.
module "clickhouse" {
  source = "github.com/meshcloud/meshstack-hub//modules/ai/clickhouse/buildingblock?ref=${var.hub.git_ref}"

  namespace          = var.clickhouse_namespace
  clickhouse_version = var.clickhouse_version
  keeper_version     = var.clickhouse_version

  clickhouse_replicas = var.clickhouse_replicas
  clickhouse_storage  = var.clickhouse_storage
  keeper_replicas     = var.clickhouse_keeper_replicas

  admin_password = random_password.clickhouse_admin.result
}
