# This mock kubeconfig is only used as a fallback when kubeconfig.yaml is not
# injected by meshStack yet (e.g. local terraform validate).
current-context: mock-context
clusters:
  - name: mock-cluster
    cluster:
      server: https://example.invalid # This must not be changed to avoid accidental usage via precondition check
      certificate-authority-data: ""
users:
  - name: mock-user
    user:
      client-certificate-data: ""
      client-key-data: ""
contexts:
  - name: mock-context
    context:
      cluster: mock-cluster
      user: mock-user
