# TODO: this is currently not used. We might provide it as an output to
# the github actions connector building block.
name: ${namespace}

on:
  push:
    branches:
      - ${branch}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${namespace}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: $${{ secrets.aks_container_registry_host }}
          username: $${{ secrets.aks_container_registry_username }}
          password: $${{ secrets.aks_container_registry_password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${registry}/${image_name}:$${{ github.sha }}

      - name: Deploy to AKS
        env:
          KUBECONFIG_CONTENT: $${{ secrets.KUBECONFIG }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "$KUBECONFIG_CONTENT" > kubeconfig
          for file in k8s/*.yml; do
            echo "Applying $file with IMAGE_TAG=$IMAGE_TAG"
            envsubst < "$file" | kubectl --kubeconfig ./kubeconfig -n ${namespace} apply -f -
          done
