name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
    uses: meshcloud/shared-workflows/.github/workflows/terraform-meshplatform-modules-build-workflow.yml@main
